---
apiVersion: apps/v1

kind: Deployment

metadata:

  name: javaapp

spec:

  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:

    metadata:

      labels:

        app: javaapp

    spec:

      containers:

      - name: javaapp

        image: kwaksconreg.azurecr.io/karooolw/pipelines-javascript-docker:latest 

        ports:

        - containerPort: 8080

          name: javaapp

      imagePullSecrets:
      - name: test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: javafront
          servicePort: 8080
        path: /(.*)
---
apiVersion: v1

kind: Service

metadata:

  name: javafront

spec:

  type: LoadBalancer

  ports:
  - port: 80
  - targetport: 8080

  selector:
    app: javaapp

