---
apiVersion: apps/v1

kind: Service

metadata:

  name: javaapp

spec:

  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:

    metadata:

      labels:

        app: javaapp

    spec:

      containers:

      - name: javaapp

        image: kwaksconreg.azurecr.io/karooolw/pipelines-javascript-docker:latest 

        ports:

        - containerPort: 8080

          name: javaapp

      imagePullSecrets:
      - name: test
---



